version: '3'

networks:
  default:
    external: true
    name: finance_default

services:
  student:
    build: .
    ports:
      - "8080:8080"
    command: /server/app
    environment:
      - FINANCE_URL=http://financeapp:8082
      - LIBRARY_URL=http://libraryapp:80
      - API_KEY=ADMIN-KEY-PASS
    depends_on:
      - mongodb
    networks:
      - default

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=UserDB
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - default

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - default